import { Routes } from '@angular/router';
import { Documentation } from './documentation/documentation';
import { Crud } from './crud/crud';
import { Empty } from './empty/empty';
import { AccountsComponent } from './accounts/accounts';
import { SettingsComponent } from './settings/settings.component';
import { PlaidIntegrationsComponent } from './plaid-integrations/plaid-integrations.component';
import { TransactionsComponent } from './transactions/transactions.component';
import { ReconciliationComponent } from './reconciliation/reconciliation.component';
import { FinancialInsightsComponent } from './financial-insights/financial-insights.component';
import { CategorizationRulesComponent } from './categorization-rules/categorization-rules.component';
import { MoneyFlowComponent } from './money-flow/money-flow.component';
import { FinancialDashboardComponent } from './financial-dashboard/financial-dashboard.component';
import { BillsComponent } from './bills/bills.component';
import { ResumeContactComponent } from './resume/resume-contact/resume-contact.component';
import { ResumeSkillsComponent } from './resume/resume-skills/resume-skills.component';
import { ResumeExperienceComponent } from './resume/resume-experience/resume-experience.component';
import { ResumeEducationComponent } from './resume/resume-education/resume-education.component';
import { ResumeCertificationsComponent } from './resume/resume-certifications/resume-certifications.component';
import { ResumeProjectsComponent } from './resume/resume-projects/resume-projects.component';
import { ResumeVolunteerComponent } from './resume/resume-volunteer/resume-volunteer.component';
import { ResumeTailoringComponent } from './resume/resume-tailoring/resume-tailoring.component';
import { ResumeCardStyleComponent } from './resume/resume-card-style/resume-card-style.component';

export default [
    { path: 'documentation', component: Documentation },
    { path: 'crud', component: Crud },
    { path: 'empty', component: Empty },
    { path: 'accounts', component: AccountsComponent },
    { path: 'settings', component: SettingsComponent },
    { path: 'plaid-integrations', component: PlaidIntegrationsComponent },
    { path: 'transactions', component: TransactionsComponent },
    { path: 'reconciliation', component: ReconciliationComponent },
    { path: 'financial-insights', component: FinancialInsightsComponent },
    { path: 'categorization-rules', component: CategorizationRulesComponent },
    { path: 'money-flow', component: MoneyFlowComponent },
    { path: 'financial-dashboard', component: FinancialDashboardComponent },
    { path: 'bills', component: BillsComponent },
    { path: 'resume/contact', component: ResumeContactComponent },
    { path: 'resume/skills', component: ResumeSkillsComponent },
    { path: 'resume/experience', component: ResumeExperienceComponent },
    { path: 'resume/education', component: ResumeEducationComponent },
    { path: 'resume/certifications', component: ResumeCertificationsComponent },
    { path: 'resume/projects', component: ResumeProjectsComponent },
    { path: 'resume/volunteer', component: ResumeVolunteerComponent },
    { path: 'resume/tailoring', component: ResumeTailoringComponent },
    { path: 'resume/card-style', component: ResumeCardStyleComponent },
    { path: '**', redirectTo: '/notfound' }
] as Routes;

